server:
  port: 8080
spring:
  application:
    name: backend
  task:
    execution:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # username-password: postgres / postgres 
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Opciones: create, create-drop, update, validate, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # Dialecto para PostgreSQL
        default_schema: transportsschema

security:
  jwt:
    secret-key: dca58f1c946f7b7ca8cfdb1c04201783b323dd281ab8be2af81db63798e8a4d4
    expiration-time: 3600000
